feat: added functionality to add reaction to chats and images in chat rooms
zurichat/zc_messaging pull request #132
Opened 2022-11-12 03:27 UTC by Johndiddles

2022-11-12 12:32 UTC, JulianaSau requested changes

2022-11-12 12:32 UTC, JulianaSau commented on frontend/zc_messaging/src/pages/message-board/index.jsx
> +      // message.emojis = emojisArray
If the code isn't being used, you can do away with it entirely. Same applies to the rest of this file. If there's any code that you commented out that you know cannot be used in the future, do away with it

2022-11-12 12:33 UTC, JulianaSau reviewed
Also, add a video instead of a screenshot showing you adding the emojis to the message

2022-11-12 15:41 UTC, Johndiddles commented
https://user-images.githubusercontent.com/48492384/201481927-07e2a5b5-88f2-4921-9fd2-398ab53c1b6e.mp4

I have removed the unused codes and attached a demo video illustrating what this PR does

2022-11-12 19:33 UTC, JulianaSau commented
@tundealabi

2022-11-12 20:42 UTC, tundealabi commented
https://user-images.githubusercontent.com/61058516/201493764-83977c24-c9aa-4a7c-9f9d-098ca77a26b3.mov

Yo @Johndiddles can't get this to work. Also, I think you need to run zuri messaging in the context of zuri main not as a standalone

2022-11-12 21:11 UTC, tundealabi commented
So you need to also clone the zuri main repo, run both projects locally.
Head over to `./packages/root-config/src/assets/plugin.importmap.json` and add this `  "@zuri/zuri-plugin-messaging": "http://localhost:5013/zuri-messaging.js"`

2022-11-13 05:03 UTC, Johndiddles commented
@tundealabi and @JulianaSau  I have made a fix for this on both zc_main and zc_messaging and here is a video of me testing it

https://user-images.githubusercontent.com/48492384/201506673-01971d17-a1aa-47ed-8fa1-4b799e83ae83.mov

2022-11-13 06:35 UTC, JulianaSau commented
Did you follow the instructions above and run zc_messaging in the context of zc_main?

2022-11-13 17:17 UTC, Johndiddles commented
Yes, I have now made a patch for the suggestions @tundealabi made earlier today.

2022-11-13 17:36 UTC, Johndiddles commented
@JulianaSau @tundealabi 

https://user-images.githubusercontent.com/48492384/201535805-9a2d259a-44b5-48c8-9226-598998270760.mp4

2022-11-13 19:16 UTC, tundealabi commented
<img width="1440" alt="Screenshot 2022-11-13 at 20 14 10" src="https://user-images.githubusercontent.com/61058516/201539851-569dee68-142a-43db-bdeb-8a2a76041c01.png">
can add and remove emojis. @JulianaSau @Johndiddles

2022-11-13 19:17 UTC, tundealabi commented
but I can't react to an emoji already added.. Not sure what the scope of the issue is though maybe that's for someone else to fix

2022-11-13 19:18 UTC, tundealabi commented
when I click on an emoji added by someone else, it throws an error

2022-11-13 19:20 UTC, JulianaSau commented
> but I can't react to an emoji already added.. Not sure what the scope of the issue is though maybe that's for someone else to fix

Yeah. That can be fixed by someone else in the future

2022-11-13 19:25 UTC, tundealabi approved these changes
cool!

2022-11-13 19:44 UTC, JulianaSau approved these changes

2022-11-13 19:55 UTC, zxenonx approved these changes

2022-11-13 19:56 UTC, merged