feat(BAC-52): added endpoint to view all files uploaded in DM
zurichat/zc_messaging pull request #146
Opened 2022-11-25 07:24 UTC by NikkyXO

2022-11-25 17:16 UTC, mikengr requested changes
Your endpoints weren't documented and is anti-pattern.
Besides that, how did you test these endpoints? @NikkyXO 
Attach screenshots if possible

2022-11-25 18:45 UTC, NikkyXO commented
> these
![Screenshot no_file1](https://user-images.githubusercontent.com/96661213/204039798-01a634ec-07ce-4ea4-9882-21a6d899a879.png)
![NoUploadedFile2](https://user-images.githubusercontent.com/96661213/204039822-c2e86102-c2b0-43d7-9669-1a0bbc940b85.jpg)

![NoUploadedFile3](https://user-images.githubusercontent.com/96661213/204039832-9dea546a-a583-4288-8586-4bb1aa05c54f.png)

I have added documentation on how i wrote the end point for viewing an files in a room .However Adequate testing couldnt be achieved, especially the one involving getting input from the endpoint handling uploading of  files
The other colleague  which this task was assigned  couldnt finish up with his task, largely due to the fact that we were assigned our various tasks in less than 24 hours.. This was an error made by the product manager who gave us wrong repo with outdated codebase to study and refactor the implemenation of all endpoint relating to file upload in a room as we were mainly freelancers from other group and given the right repo in less than 24 hours when the mistake was realised

2022-11-25 22:45 UTC, mikengr requested changes
@NikkyXO your changes have been observed, but your screenshots don't show that this endpoint will do what you say it does. Please kindly show a screenshot of the response gotten when this endpoint is called

2022-11-25 22:45 UTC, mikengr commented on backend/endpoints/file.py
>  @router.get("/get/files/{org_id}/{room_id}")
this url path is wrongly defined, check the codebase and observe the url naming patterns

2022-11-25 22:45 UTC, mikengr commented on backend/endpoints/file.py
> +        print(fname,fdir)
don't push print statements

2022-11-25 22:45 UTC, mikengr commented on backend/endpoints/file.py
>      resp = Response(data.getvalue(), media_type="image/png", headers={
name your variables properly with meaningful names

2022-11-25 23:19 UTC, AI-fae requested changes

2022-11-25 23:19 UTC, AI-fae commented on backend/endpoints/file.py
> +@router.get("/get/files/{org_id}/{room_id}")
```suggestion
@router.get("/org/{org_id}/rooms/{room_id}/files")
```
your endpoint should look like this instead

2022-11-25 23:19 UTC, AI-fae commented on backend/endpoints/file.py
> +                str(list_files)
what is the difference between line 96 and 97?

2022-11-25 23:19 UTC, AI-fae commented on backend/endpoints/file.py
> +
Please no 3 level nesting for readability sake.
You could use negative conditionals instead. example:

```suggestion
  if not messages:
       raise Exception
  list_files = []
  for message in messages:
      code block
 if not list_files:
     raise Exception
 list_files ...

 
            
  
```

2022-11-25 23:19 UTC, AI-fae commented on backend/main.py
> +from endpoints import members, messages, rooms, sync, threads, file
the file name should always be in plural to communicate processing of multiple resource.
so rename `file.py` to `files.py`

2022-11-25 23:21 UTC, AI-fae commented
Good job!
I have concerns your changes might not work as expected.
kindly record a screen recording of your testing process

2022-11-26 05:57 UTC, closed without merging

2022-11-26 06:13 UTC, NikkyXO commented
good morning sir,
 i have made required changes to the end point  and here is  the required
screen shot  of the endpoint testings

The screenshots are as follows
A screenshot  was done while getting the message list and retrieving empty
files no files where uploaded then
because Uploading through the Upload file endpoint was unavailable as the
task is unfinished by another, and the send messages endpoint
kep giving 422 error, i used a dummy urlpath for testing the endpoint and
helper zipfile file function
screenshot was done while trying to retrieve and view archive files

the screenshots are attached below, thanks for your kind patience

yours sincerely
olanike ogundiran
[image: CheckingArchiveFile.png]
[image: dummyurlpath.png][image: extract3.png][image:
extractArchive.png][image:
extractedArchive.png][image: list_of_files.png][image:
List_of_uploaded_files.png]

On Sat, Nov 26, 2022 at 12:21 AM AI-fae ***@***.***> wrote:

> Good job!
> I have concerns your changes might not work as expected.
> kindly record a screen recording of your testing process
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zurichat/zc_messaging/pull/146#issuecomment-1327927691>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXBO5XL6IP7LX2P5W7IDHPLWKFCZFANCNFSM6AAAAAASLA7YVM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-26 06:28 UTC, NikkyXO commented
here is the link to the Pulll Request:
https://github.com/zurichat/zc_messaging/pull/146

On Sat, Nov 26, 2022 at 7:13 AM olanike ***@***.***> wrote:

> good morning sir,
>  i have made required changes to the end point  and here is  the required
> screen shot  of the endpoint testings
>
> The screenshots are as follows
> A screenshot  was done while getting the message list and retrieving empty
> files no files where uploaded then
> because Uploading through the Upload file endpoint was unavailable as the
> task is unfinished by another, and the send messages endpoint
> kep giving 422 error, i used a dummy urlpath for testing the endpoint and
> helper zipfile file function
> screenshot was done while trying to retrieve and view archive files
>
> the screenshots are attached below, thanks for your kind patience
>
> yours sincerely
> olanike ogundiran
> [image: CheckingArchiveFile.png]
> [image: dummyurlpath.png][image: extract3.png][image: extractArchive.png][image:
> extractedArchive.png][image: list_of_files.png][image:
> List_of_uploaded_files.png]
>
> On Sat, Nov 26, 2022 at 12:21 AM AI-fae ***@***.***> wrote:
>
>> Good job!
>> I have concerns your changes might not work as expected.
>> kindly record a screen recording of your testing process
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/zurichat/zc_messaging/pull/146#issuecomment-1327927691>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AXBO5XL6IP7LX2P5W7IDHPLWKFCZFANCNFSM6AAAAAASLA7YVM>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-11-26 10:09 UTC, NikkyXO commented
i unintentional made a git push -force from my branch while pushing to
github , this closed the previous pull request i made
here is the new pull request:
https://github.com/zurichat/zc_messaging/pull/155

Apologies for the inconvenience
yours sincerely
olanike

On Sat, Nov 26, 2022 at 7:28 AM olanike ***@***.***> wrote:

> here is the link to the Pulll Request:
> https://github.com/zurichat/zc_messaging/pull/146
>
> On Sat, Nov 26, 2022 at 7:13 AM olanike ***@***.***> wrote:
>
>> good morning sir,
>>  i have made required changes to the end point  and here is  the required
>> screen shot  of the endpoint testings
>>
>> The screenshots are as follows
>> A screenshot  was done while getting the message list and
>> retrieving empty files no files where uploaded then
>> because Uploading through the Upload file endpoint was unavailable as the
>> task is unfinished by another, and the send messages endpoint
>> kep giving 422 error, i used a dummy urlpath for testing the endpoint and
>> helper zipfile file function
>> screenshot was done while trying to retrieve and view archive files
>>
>> the screenshots are attached below, thanks for your kind patience
>>
>> yours sincerely
>> olanike ogundiran
>> [image: CheckingArchiveFile.png]
>> [image: dummyurlpath.png][image: extract3.png][image: extractArchive.png][image:
>> extractedArchive.png][image: list_of_files.png][image:
>> List_of_uploaded_files.png]
>>
>> On Sat, Nov 26, 2022 at 12:21 AM AI-fae ***@***.***> wrote:
>>
>>> Good job!
>>> I have concerns your changes might not work as expected.
>>> kindly record a screen recording of your testing process
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/zurichat/zc_messaging/pull/146#issuecomment-1327927691>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AXBO5XL6IP7LX2P5W7IDHPLWKFCZFANCNFSM6AAAAAASLA7YVM>
>>> .
>>> You are receiving this because you were mentioned.Message ID:
>>> ***@***.***>
>>>
>>