Feat/bac 55 adding upload function data storage
zurichat/zc_messaging pull request #157
Opened 2022-11-26 14:22 UTC by devvspaces

- Created data storage function to upload files to zc_core
- Handled all error edge cases
- Wrote tests for all cases

Linear: https://linear.app/team-socket/issue/BAC-55/implementing-the-data-storage-upload-function-to-upload-one-or-more

2022-11-27 06:01 UTC, AI-fae requested changes, later dismissed

2022-11-27 06:01 UTC, FlorenceEgwu commented on backend/requirements.txt
> +httptools==0.5.0
take out the versioning on this  completely. I think this still gives issue for some people.
i.e we should have
```suggestion
httptools
```

2022-11-27 06:01 UTC, FlorenceEgwu commented on backend/tests/utils/test_db.py
> +            }
great job on adding these test cases. Really happy with it.

2022-11-27 06:01 UTC, FlorenceEgwu commented on backend/utils/db.py
> +
I thought headers like this were handled somewhere central in this class.
@zxenonx , can you remember?

2022-11-27 06:01 UTC, FlorenceEgwu commented on backend/utils/db.py
> +        self, files: List[Any], token: str
`files_upload` would be a more descriptive name for this method

2022-11-27 06:03 UTC, AI-fae commented
Great job on this.
I have added a few comments

2022-11-27 07:01 UTC, devvspaces commented on backend/utils/db.py
> +        self, files: List[Any], token: str
Okay thanks, I will make the required changes

2022-11-27 22:29 UTC, zxenonx approved these changes
Good job

2022-11-27 22:29 UTC, zxenonx commented on backend/utils/db.py
> +
@AI-fae, I remember we did this in zc_plugin_dm but not here.
Besides, we need to protect these endpoints now.

2022-11-27 22:29 UTC, zxenonx commented on backend/utils/message_utils.py
> +from typing import Any, Dict, List, Optional
We no longer need to import List and Dict from Python 3.9.
https://peps.python.org/pep-0585/
list and dict can be used. They are built in

2022-11-27 22:30 UTC, zxenonx commented on backend/utils/message_utils.py
> +from typing import Any, Dict, List, Optional
@devvspaces

2022-11-28 17:12 UTC, mikengr approved these changes
LGTM

2022-11-28 17:16 UTC, merged