Thread Page Fix For Frontend and Backend
zurichat/zc_messaging pull request #199
Opened 2022-12-12 23:44 UTC by Harrylever

2022-12-13 18:05 UTC, JulianaSau requested changes

2022-12-13 18:05 UTC, JulianaSau commented on frontend/zc_messaging/src/pages/threads/threads.utils.js
> +        // `${BASE_URL}/org/${orgId}/member/${senderId}/threads`
Remove this commented out code

2022-12-13 18:05 UTC, JulianaSau commented on frontend/zc_messaging/src/component/ThreadList/index.jsx
> +      <ThreadItem key={index} Thread={message} />
Use a better key. It's not advisable to use the index from the array directly like that. Make it more unique to the thread items

2022-12-13 18:05 UTC, JulianaSau commented on frontend/zc_messaging/src/component/ThreadList/ThreadItem/index.jsx
> +          key={index.toString()}
Same thing here for this index

2022-12-13 18:06 UTC, JulianaSau commented
@mykie88 Please help to review the backend code in this PR

2022-12-14 08:53 UTC, Harrylever commented on frontend/zc_messaging/src/component/ThreadList/ThreadItem/index.jsx
> +          key={index.toString()}
Honestly, there's no key of the thread object that has a unique attribute value to fit in as the key. But I'll see if I still change it.

2022-12-14 08:53 UTC, Harrylever commented on frontend/zc_messaging/src/component/ThreadList/index.jsx
> +      <ThreadItem key={index} Thread={message} />
Okay

2022-12-14 14:46 UTC, JulianaSau commented on frontend/zc_messaging/src/component/ThreadList/ThreadItem/index.jsx
> +          key={index.toString()}
You could simply use the thread ID that comes with the messages.

2022-12-14 14:58 UTC, mikengr requested changes
@Harrylever I left some comments
Also, it seems you have been deactivated, what happened?

2022-12-14 14:58 UTC, mikengr commented on backend/endpoints/threads.py
> +        single_room_resp = await get_room_messages_for_threads(org_id, room_id)
`get_room_threaded_messages` is a better name for this function and the variable should `threaded_messages`

Also I don't think this your for loop is doing the correct logic as intended

2022-12-14 14:58 UTC, mikengr commented on backend/endpoints/threads.py
>              pass
this if statement should be joined with the next one

2022-12-14 14:58 UTC, mikengr commented on backend/utils/message_utils.py
> +async def get_room_messages_for_threads(
this function will just return the same result as `get_room_messages` excluding pagination. If you want to write a utility function that returns threaded messages, then the logic should be different from that go get room messages.

2022-12-14 14:58 UTC, mikengr commented on backend/utils/message_utils.py
> +    options = {"limit": size, "skip": skip, "sort": { "created_at": 1}}
is there a reason for modifying the sort option?

2023-03-16 04:56 UTC, closed without merging