Sidebar endpoint
zurichat/zc_messaging pull request #22
Opened 2021-11-28 14:24 UTC by o4codes

Endpoints for the getting side bar content is created

2021-11-28 17:01 UTC, zxenonx requested changes

2021-11-28 17:01 UTC, zxenonx commented on backend/endpoints/sync.py
> +@router.get("/sidebar")
The router annotation needs more information: `status_code, response_model, responses`

2021-11-28 17:01 UTC, zxenonx commented on backend/endpoints/sync.py
> +        [dict]: dict containing sidebar data with status code 200
`Returns` comes before `Raises`

2021-11-28 17:01 UTC, zxenonx commented on backend/endpoints/sync.py
> +async def get_sidebar(org_id: str, member_id: str, room_type: RoomType):
```suggestion
async def get_sidebar(org_id: ObjectId, member_id: str, room_type: RoomType):
```
`org_id` parameter can now be of type `ObjectId`, right?

2021-11-28 17:01 UTC, zxenonx commented on backend/utils/sidebar.py
> +            "plugin_id": "messaging.zuri.chat",
It's rather chat.zuri.chat

2021-11-28 17:01 UTC, zxenonx commented on backend/utils/sidebar.py
> -    async def __get_dm_room_image_url(cls, room_members: dict) -> str:
Are the class methods no longer async?

2021-11-28 17:03 UTC, zxenonx commented
Thanks @o4codes. Just a few changes needed.

2021-11-28 17:05 UTC, o4codes commented on backend/endpoints/sync.py
> +async def get_sidebar(org_id: str, member_id: str, room_type: RoomType):
Tried this, the server will not run because it complains of ObjectID not being a pyndantic data type

2021-11-28 17:21 UTC, o4codes commented on backend/endpoints/sync.py
> +@router.get("/sidebar")
fixed

2021-11-28 17:21 UTC, o4codes commented on backend/endpoints/sync.py
> +        [dict]: dict containing sidebar data with status code 200
fixed

2021-11-28 17:22 UTC, o4codes commented on backend/utils/sidebar.py
> +            "plugin_id": "messaging.zuri.chat",
fixed

2021-11-28 17:30 UTC, o4codes commented on backend/utils/sidebar.py
> -    async def __get_dm_room_image_url(cls, room_members: dict) -> str:
fixed

2021-11-28 17:32 UTC, o4codes commented
@zxenonx thanks for the reviews.
The code reviews has been put into place

2021-11-28 19:30 UTC, zxenonx commented on backend/endpoints/sync.py
> +async def get_sidebar(org_id: str, member_id: str, room_type: RoomType):
Oh, ok

2021-11-28 19:33 UTC, zxenonx approved these changes

2021-11-28 19:34 UTC, merged

2021-11-30 16:01 UTC, AI-fae reviewed
Great work