Refactor
zurichat/zc_messaging pull request #37
Opened 2021-12-05 18:56 UTC by o4codes

Made some few refactorings.
1. Validated all DM, GROUP DM rooms are set to private
2. Removed the install class and replaced it with request body directly in the function parameters because the class will not be reusable.

2021-12-05 20:33 UTC, mykie88 reviewed
Well done Chief I left some comments.

2021-12-05 20:33 UTC, mikenrowland commented on backend/endpoints/sync.py
> +            user_id: {"role": Role.ADMIN, "starred": False, "closed": False}
Seen. I've tried this though, not exactly the same way but something similar and the "Role.ADMIN" part was throwing an error when I tried to update the room using DB.update.
But I will still check it and see if it solves the problem. Thanks

2021-12-05 20:33 UTC, mikenrowland commented on backend/schema/room.py
> +        values["is_private"] = True
Is this supposed to be outside of the first 'IF' block at line 83? because I think this will end up setting "is_private" field for Channels to TRUE too.
@o4codes

2021-12-05 22:04 UTC, zxenonx requested changes

2021-12-05 22:04 UTC, zxenonx commented on backend/endpoints/sync.py
> +@router.post("/install")
Please, kindly complete with `status_code` and `responses`

2021-12-05 22:04 UTC, zxenonx commented on backend/endpoints/sync.py
> +async def dm_install(organisation_id: str = Body(...), user_id: str = Body(...)):
👍

2021-12-05 22:04 UTC, zxenonx commented on backend/schema/room.py
> +        values["is_private"] = True
Yes, indeed. I think this is a mistake @o4codes

2021-12-05 22:08 UTC, zxenonx commented
Thanks for the refactoring @o4codes

2021-12-06 04:21 UTC, o4codes commented on backend/endpoints/sync.py
> +            user_id: {"role": Role.ADMIN, "starred": False, "closed": False}
Alright

2021-12-06 04:32 UTC, o4codes commented on backend/endpoints/sync.py
> +@router.post("/install")
Thanks Fixed

2021-12-06 04:33 UTC, o4codes commented on backend/schema/room.py
> +        values["is_private"] = True
Thanks, Fixed

2021-12-06 04:34 UTC, o4codes commented
@zxenonx 
@mykie88 

Thanks for the reviews.
The reviews have been effected

2021-12-06 08:25 UTC, zxenonx approved these changes
Thanks @o4codes  for the changes.
LGTM.

2021-12-06 08:35 UTC, merged

2021-12-06 10:34 UTC, AI-fae commented
Looks good to me.
Well than @o4codes .