Updated remove member endpoint
zurichat/zc_messaging pull request #89
Opened 2022-01-26 12:54 UTC by kinglighthill

- Modified rooms.py remove_member function. Added a None check to admin_id on line 130 because admin_id is optional
- Modified rooms_utils.py remove_room_member function. Changed the dict key from '_id' to 'id' on lines 150 and 160

2022-01-27 12:27 UTC, man-of-mind approved these changes
Well done boss

2022-01-27 15:38 UTC, pauline-banye requested changes
hi @kinglighthill I left a comment

2022-01-27 15:38 UTC, pauline-banye commented on backend/endpoints/rooms.py
>              detail="admin id specified not a member of the room",
Okay, I just tested the endpoint. I couldn't remove a regular member from a channel with or without an admin_id. this is what's returned.
{
  "detail": "\"unable to remove room member\""
}

2022-01-27 19:24 UTC, mykie88 approved these changes
well done

2022-01-28 17:37 UTC, pauline-banye approved these changes

2022-01-28 17:37 UTC, pauline-banye commented on backend/utils/room_utils.py
> +    response["room_id"] = room_data["id"]
Working now. 👍🏻👍🏻

2022-01-28 22:42 UTC, zxenonx requested changes
Good work @kinglighthill.
I left some comments.

2022-01-28 22:42 UTC, zxenonx commented on backend/utils/room_utils.py
>      response = update_room["data"]
We can remove matched & modified documents from the response:

```json
{
  "status": "success",
  "message": "user removed from room successfully",
  "data": {
    "matched_documents": 1,
    "modified_documents": 1,
    "member_id": "61e59f1b65934b58b8e5d1cb",
    "room_id": "61e72d1265934b58b8e5d220"
  }
}
```

2022-01-28 22:42 UTC, zxenonx commented on backend/endpoints/rooms.py
>              detail="admin id specified not a member of the room",
I tested with this room (`61e72d1265934b58b8e5d220`, Channel).
The room had only a member who is the admin, `61e59f1b65934b58b8e5d1cb`.
I was able to remove the admin by passing the admin id to both **member_id** and **admin_id** parameters.
Now, the room has no members as the admin has been removed.

This shouldn't be possible, right? @kinglighthill

2022-01-28 22:42 UTC, zxenonx commented on backend/utils/room_utils.py
> +    response["room_id"] = room_id
We can also do something like this:

`response.update({"member_id": member_id, "room_id": room_id})`

2022-02-03 11:51 UTC, pauline-banye approved these changes
well done @kinglighthill. Channel owner is restricted from leaving channel, thus room cannot be empty.

2022-02-03 11:51 UTC, paulinebanye commented on backend/endpoints/rooms.py
> +            detail="cannot removed yourself"
```suggestion
            detail="cannot remove yourself"
```

2022-02-03 14:20 UTC, pauline-banye commented on backend/endpoints/rooms.py
> +        )
lines 136 - 140 is completely unnecessary IMO. The endpoint already does what its supposed to without it..

2022-02-06 10:15 UTC, zxenonx approved these changes
Thanks @kinglighthill for the changes.

2022-02-06 10:17 UTC, merged